//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""d321dc61-cc10-46c5-927f-d1a17368c1a9"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6aff9f1a-abe2-4af8-b916-dd35c49d3692"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""Button"",
                    ""id"": ""064e01bd-1db2-45d6-8437-225c4885a12b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""3bcb3fac-9d99-4a6d-a384-039cb2e52657"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""07d6750d-d892-44f1-98ec-7f01e8f0520c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Target"",
                    ""type"": ""Button"",
                    ""id"": ""6940e1f0-451b-4399-830a-b6f42f6cee7a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""0fafcdc5-41b3-460c-a3e4-f2ca135155c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""56b3d94e-41c5-4b1b-b588-244d895e1d0d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DetachPart"",
                    ""type"": ""Button"",
                    ""id"": ""124e3a7d-5fa8-4874-976b-433609ae545a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReattachPart"",
                    ""type"": ""Button"",
                    ""id"": ""53f18129-8efa-4316-b9c7-bf2c97e05fc9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootR"",
                    ""type"": ""Button"",
                    ""id"": ""6f849afc-a52a-435c-ad9d-ccd21a5e3df5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootL"",
                    ""type"": ""Button"",
                    ""id"": ""31eae7bc-0ac9-47a3-a52b-c296573e71e8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropEverything"",
                    ""type"": ""Button"",
                    ""id"": ""c08f4d23-08b4-42f8-9dd2-811ad333e15f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropLeftArm"",
                    ""type"": ""Button"",
                    ""id"": ""247aea5f-4013-4542-a2e3-f57ef7f6a471"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropRightArm"",
                    ""type"": ""Button"",
                    ""id"": ""2ab0b7f1-46e1-41c1-aaeb-03c5e1d152b4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropRightLeg"",
                    ""type"": ""Button"",
                    ""id"": ""689dd30b-159b-4e2e-a8fa-ce9c5a58e011"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropLeftLeg"",
                    ""type"": ""Button"",
                    ""id"": ""98872a10-9f48-40e4-adb1-836cd3772eb2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropBothLegs"",
                    ""type"": ""Button"",
                    ""id"": ""8e243c7c-f5dc-4103-8fbe-0ef9dc451e61"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RecallBothArms"",
                    ""type"": ""Button"",
                    ""id"": ""cf02c858-c701-4056-bf57-793bdc945252"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RecallLeftArm"",
                    ""type"": ""Button"",
                    ""id"": ""ba31818a-56d3-40cd-a041-aa540b08ff11"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RecallRightArm"",
                    ""type"": ""Button"",
                    ""id"": ""d8db479a-a042-435a-96d4-dff55d89267a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""fef3cda6-9797-41e9-bf68-b6477edb5cfc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aiming"",
                    ""type"": ""Button"",
                    ""id"": ""e7e82724-6920-4f39-9f48-5adf20541be6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""535c5f66-8446-40bc-ad25-f201b27f6a80"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse & Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e86bf97d-37db-4c3e-92e7-4d9b249c1c6a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41508a5e-b998-4994-a52d-a5ed2d966db7"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse & Keyboard"",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6389042d-439e-47fb-bc0c-57c9ea5dd5e0"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73c13e9a-2cf2-4ce2-8fb5-876410fa9bf8"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a0d7892d-dc31-4268-a290-71ec3cc848c5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e9c8cec1-dca0-46e4-a8e3-c849d4df1827"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c09432dc-2108-4657-9f27-4e205c6c1fa4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""47275a99-31fb-4349-a071-5ca00174c7ab"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""13e94e23-a7f1-45da-901b-752325e46ece"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""adec5906-2765-4bb9-b6e8-1d5ce8a24c70"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c23e2617-49d9-4e4c-b019-e1eadce7affa"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f60f3c14-bf9d-4424-a36b-c3a41d6dbf76"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6713c18a-6da6-47cd-982d-12e42995f971"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3b0d4279-4986-453f-95af-682a3b8c56bb"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c738f09f-b268-4b1e-97ba-62c59daf0b24"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse & Keyboard"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67a96e3a-c545-490c-a275-b4dfc6f665ca"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eeacfbfe-b9e6-4a00-97dd-99a5fa3d1702"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6efa3a1-c9dd-4cf5-871f-ecd89dac53d7"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b4a69ff-9afa-434d-953e-73db48998142"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5a56d8a-1a23-4f37-a7fb-4be01bff5790"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b79e2e01-dc15-4df3-b45a-c0698584f34d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Mouse & Keyboard"",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21440669-f250-4848-b23f-b9a9c557a1e1"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95c83228-9dee-491b-88b6-83b1f22595e6"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DetachPart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04ad30f6-d959-4220-97c1-8976c5cc6a1e"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReattachPart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7aaa717d-0645-4d0f-9636-a0ab7e0ab1fd"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReattachPart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98bb21e0-252c-4ad7-a384-c984567d5921"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3c695b6-1c04-4390-bf23-65de625ab82e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""ShootR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b37cd96-cabd-493e-8c6c-2aa8ea62d2b2"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac677564-e9c9-4e5f-850a-90f9735fcf5a"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""ShootL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97fdca3f-8a29-488a-ab0d-2bd5740dad41"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropEverything"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04f90b53-28c0-4c20-8372-5974bb07f95b"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropEverything"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f93079da-9f10-4296-b43b-ae8837d19a0e"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropLeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""964987f7-dd00-47e3-b3ed-8b60c0110888"",
                    ""path"": ""<Keyboard>/leftBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropLeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a25d5fc-7912-4ec8-b8cd-1146ffea6960"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropRightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f076b8e-04c4-4c32-8a4e-bcdb2779e42a"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropRightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b5d8309-cf20-4d1b-b72a-ef7d54c8328d"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropRightLeg"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""212d4f86-db7d-4dfb-89d2-701400fcfaf7"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropRightLeg"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73f8d61c-6d9a-4561-ab01-75972422af3d"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropLeftLeg"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab8663a5-7815-4b47-9646-b1eef0fd9dbb"",
                    ""path"": ""<Keyboard>/quote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropLeftLeg"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e51351b8-b58f-429a-8e1e-6f130a1d5b2b"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropBothLegs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bba299a-41ef-4b34-9cf3-700bebf71ef6"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropBothLegs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""567a685a-bb39-4351-a57f-389a226ba064"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecallBothArms"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7c72937-0315-41a2-894c-d4e8956c0d1d"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecallBothArms"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dde36e41-fcd2-41fe-9422-8a5e2e64f79a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecallLeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45b8b63d-616e-4cd2-84c6-1ef0341b6116"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecallRightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41625378-5893-4ccf-854a-8d2f60fb7217"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecallRightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21babd6d-ea9a-4c20-82a0-862b70c32287"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7782c5b0-07cc-47d7-8087-16d7f318abac"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c604384-e54a-4da2-9557-bb3e4f3a8495"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccec70ee-4417-480c-bb6d-3e2f6b04c036"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse & Keyboard"",
            ""bindingGroup"": ""Mouse & Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Dodge = m_Player.FindAction("Dodge", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Target = m_Player.FindAction("Target", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_Block = m_Player.FindAction("Block", throwIfNotFound: true);
        m_Player_DetachPart = m_Player.FindAction("DetachPart", throwIfNotFound: true);
        m_Player_ReattachPart = m_Player.FindAction("ReattachPart", throwIfNotFound: true);
        m_Player_ShootR = m_Player.FindAction("ShootR", throwIfNotFound: true);
        m_Player_ShootL = m_Player.FindAction("ShootL", throwIfNotFound: true);
        m_Player_DropEverything = m_Player.FindAction("DropEverything", throwIfNotFound: true);
        m_Player_DropLeftArm = m_Player.FindAction("DropLeftArm", throwIfNotFound: true);
        m_Player_DropRightArm = m_Player.FindAction("DropRightArm", throwIfNotFound: true);
        m_Player_DropRightLeg = m_Player.FindAction("DropRightLeg", throwIfNotFound: true);
        m_Player_DropLeftLeg = m_Player.FindAction("DropLeftLeg", throwIfNotFound: true);
        m_Player_DropBothLegs = m_Player.FindAction("DropBothLegs", throwIfNotFound: true);
        m_Player_RecallBothArms = m_Player.FindAction("RecallBothArms", throwIfNotFound: true);
        m_Player_RecallLeftArm = m_Player.FindAction("RecallLeftArm", throwIfNotFound: true);
        m_Player_RecallRightArm = m_Player.FindAction("RecallRightArm", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_Aiming = m_Player.FindAction("Aiming", throwIfNotFound: true);
    }

    ~@Controls()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, Controls.Player.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Dodge;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Target;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_Block;
    private readonly InputAction m_Player_DetachPart;
    private readonly InputAction m_Player_ReattachPart;
    private readonly InputAction m_Player_ShootR;
    private readonly InputAction m_Player_ShootL;
    private readonly InputAction m_Player_DropEverything;
    private readonly InputAction m_Player_DropLeftArm;
    private readonly InputAction m_Player_DropRightArm;
    private readonly InputAction m_Player_DropRightLeg;
    private readonly InputAction m_Player_DropLeftLeg;
    private readonly InputAction m_Player_DropBothLegs;
    private readonly InputAction m_Player_RecallBothArms;
    private readonly InputAction m_Player_RecallLeftArm;
    private readonly InputAction m_Player_RecallRightArm;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_Aiming;
    public struct PlayerActions
    {
        private @Controls m_Wrapper;
        public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Dodge => m_Wrapper.m_Player_Dodge;
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Target => m_Wrapper.m_Player_Target;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @Block => m_Wrapper.m_Player_Block;
        public InputAction @DetachPart => m_Wrapper.m_Player_DetachPart;
        public InputAction @ReattachPart => m_Wrapper.m_Player_ReattachPart;
        public InputAction @ShootR => m_Wrapper.m_Player_ShootR;
        public InputAction @ShootL => m_Wrapper.m_Player_ShootL;
        public InputAction @DropEverything => m_Wrapper.m_Player_DropEverything;
        public InputAction @DropLeftArm => m_Wrapper.m_Player_DropLeftArm;
        public InputAction @DropRightArm => m_Wrapper.m_Player_DropRightArm;
        public InputAction @DropRightLeg => m_Wrapper.m_Player_DropRightLeg;
        public InputAction @DropLeftLeg => m_Wrapper.m_Player_DropLeftLeg;
        public InputAction @DropBothLegs => m_Wrapper.m_Player_DropBothLegs;
        public InputAction @RecallBothArms => m_Wrapper.m_Player_RecallBothArms;
        public InputAction @RecallLeftArm => m_Wrapper.m_Player_RecallLeftArm;
        public InputAction @RecallRightArm => m_Wrapper.m_Player_RecallRightArm;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @Aiming => m_Wrapper.m_Player_Aiming;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Dodge.started += instance.OnDodge;
            @Dodge.performed += instance.OnDodge;
            @Dodge.canceled += instance.OnDodge;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Target.started += instance.OnTarget;
            @Target.performed += instance.OnTarget;
            @Target.canceled += instance.OnTarget;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Block.started += instance.OnBlock;
            @Block.performed += instance.OnBlock;
            @Block.canceled += instance.OnBlock;
            @DetachPart.started += instance.OnDetachPart;
            @DetachPart.performed += instance.OnDetachPart;
            @DetachPart.canceled += instance.OnDetachPart;
            @ReattachPart.started += instance.OnReattachPart;
            @ReattachPart.performed += instance.OnReattachPart;
            @ReattachPart.canceled += instance.OnReattachPart;
            @ShootR.started += instance.OnShootR;
            @ShootR.performed += instance.OnShootR;
            @ShootR.canceled += instance.OnShootR;
            @ShootL.started += instance.OnShootL;
            @ShootL.performed += instance.OnShootL;
            @ShootL.canceled += instance.OnShootL;
            @DropEverything.started += instance.OnDropEverything;
            @DropEverything.performed += instance.OnDropEverything;
            @DropEverything.canceled += instance.OnDropEverything;
            @DropLeftArm.started += instance.OnDropLeftArm;
            @DropLeftArm.performed += instance.OnDropLeftArm;
            @DropLeftArm.canceled += instance.OnDropLeftArm;
            @DropRightArm.started += instance.OnDropRightArm;
            @DropRightArm.performed += instance.OnDropRightArm;
            @DropRightArm.canceled += instance.OnDropRightArm;
            @DropRightLeg.started += instance.OnDropRightLeg;
            @DropRightLeg.performed += instance.OnDropRightLeg;
            @DropRightLeg.canceled += instance.OnDropRightLeg;
            @DropLeftLeg.started += instance.OnDropLeftLeg;
            @DropLeftLeg.performed += instance.OnDropLeftLeg;
            @DropLeftLeg.canceled += instance.OnDropLeftLeg;
            @DropBothLegs.started += instance.OnDropBothLegs;
            @DropBothLegs.performed += instance.OnDropBothLegs;
            @DropBothLegs.canceled += instance.OnDropBothLegs;
            @RecallBothArms.started += instance.OnRecallBothArms;
            @RecallBothArms.performed += instance.OnRecallBothArms;
            @RecallBothArms.canceled += instance.OnRecallBothArms;
            @RecallLeftArm.started += instance.OnRecallLeftArm;
            @RecallLeftArm.performed += instance.OnRecallLeftArm;
            @RecallLeftArm.canceled += instance.OnRecallLeftArm;
            @RecallRightArm.started += instance.OnRecallRightArm;
            @RecallRightArm.performed += instance.OnRecallRightArm;
            @RecallRightArm.canceled += instance.OnRecallRightArm;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Aiming.started += instance.OnAiming;
            @Aiming.performed += instance.OnAiming;
            @Aiming.canceled += instance.OnAiming;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Dodge.started -= instance.OnDodge;
            @Dodge.performed -= instance.OnDodge;
            @Dodge.canceled -= instance.OnDodge;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Target.started -= instance.OnTarget;
            @Target.performed -= instance.OnTarget;
            @Target.canceled -= instance.OnTarget;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Block.started -= instance.OnBlock;
            @Block.performed -= instance.OnBlock;
            @Block.canceled -= instance.OnBlock;
            @DetachPart.started -= instance.OnDetachPart;
            @DetachPart.performed -= instance.OnDetachPart;
            @DetachPart.canceled -= instance.OnDetachPart;
            @ReattachPart.started -= instance.OnReattachPart;
            @ReattachPart.performed -= instance.OnReattachPart;
            @ReattachPart.canceled -= instance.OnReattachPart;
            @ShootR.started -= instance.OnShootR;
            @ShootR.performed -= instance.OnShootR;
            @ShootR.canceled -= instance.OnShootR;
            @ShootL.started -= instance.OnShootL;
            @ShootL.performed -= instance.OnShootL;
            @ShootL.canceled -= instance.OnShootL;
            @DropEverything.started -= instance.OnDropEverything;
            @DropEverything.performed -= instance.OnDropEverything;
            @DropEverything.canceled -= instance.OnDropEverything;
            @DropLeftArm.started -= instance.OnDropLeftArm;
            @DropLeftArm.performed -= instance.OnDropLeftArm;
            @DropLeftArm.canceled -= instance.OnDropLeftArm;
            @DropRightArm.started -= instance.OnDropRightArm;
            @DropRightArm.performed -= instance.OnDropRightArm;
            @DropRightArm.canceled -= instance.OnDropRightArm;
            @DropRightLeg.started -= instance.OnDropRightLeg;
            @DropRightLeg.performed -= instance.OnDropRightLeg;
            @DropRightLeg.canceled -= instance.OnDropRightLeg;
            @DropLeftLeg.started -= instance.OnDropLeftLeg;
            @DropLeftLeg.performed -= instance.OnDropLeftLeg;
            @DropLeftLeg.canceled -= instance.OnDropLeftLeg;
            @DropBothLegs.started -= instance.OnDropBothLegs;
            @DropBothLegs.performed -= instance.OnDropBothLegs;
            @DropBothLegs.canceled -= instance.OnDropBothLegs;
            @RecallBothArms.started -= instance.OnRecallBothArms;
            @RecallBothArms.performed -= instance.OnRecallBothArms;
            @RecallBothArms.canceled -= instance.OnRecallBothArms;
            @RecallLeftArm.started -= instance.OnRecallLeftArm;
            @RecallLeftArm.performed -= instance.OnRecallLeftArm;
            @RecallLeftArm.canceled -= instance.OnRecallLeftArm;
            @RecallRightArm.started -= instance.OnRecallRightArm;
            @RecallRightArm.performed -= instance.OnRecallRightArm;
            @RecallRightArm.canceled -= instance.OnRecallRightArm;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Aiming.started -= instance.OnAiming;
            @Aiming.performed -= instance.OnAiming;
            @Aiming.canceled -= instance.OnAiming;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_MouseKeyboardSchemeIndex = -1;
    public InputControlScheme MouseKeyboardScheme
    {
        get
        {
            if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse & Keyboard");
            return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnDodge(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnTarget(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnDetachPart(InputAction.CallbackContext context);
        void OnReattachPart(InputAction.CallbackContext context);
        void OnShootR(InputAction.CallbackContext context);
        void OnShootL(InputAction.CallbackContext context);
        void OnDropEverything(InputAction.CallbackContext context);
        void OnDropLeftArm(InputAction.CallbackContext context);
        void OnDropRightArm(InputAction.CallbackContext context);
        void OnDropRightLeg(InputAction.CallbackContext context);
        void OnDropLeftLeg(InputAction.CallbackContext context);
        void OnDropBothLegs(InputAction.CallbackContext context);
        void OnRecallBothArms(InputAction.CallbackContext context);
        void OnRecallLeftArm(InputAction.CallbackContext context);
        void OnRecallRightArm(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnAiming(InputAction.CallbackContext context);
    }
}
